name: Dodgebolt
api: 3.0.0
version: 1.0.0
main: WC\Dodgebolt\Dodgebolt

permissions:
  db.cmd:
    description: Permission to all the dodgebolt commands
    default: op
    children:
      db.cmd.help:
        description: Permission for /db help
        default: op
      db.cmd.create:
        description: Permission for /db make
        default: op
      db.cmd.remove:
        description: Permission for /db delete
        default: op
      db.cmd.setup:
        description: Permission for /db set
        default: op
      db.cmd.arenas:
        description: Permission for /db arenas
        default: op
      db.cmd.join:
        description: Permission for /db join
        default: true
      db.cmd.shop:
        description: Permission for /db shop
        default: true
