name: SumoByMcMelonTV
api: 3.0.0
version: 1.0.0
main: jack\sumo\Sumo

permissions:
  1vs1.cmd:
    description: Permission to all the sumo commands
    default: op
    children:
      sumo.cmd.help:
        description: Permission for /sumo help
        default: op
      sumo.cmd.create:
        description: Permission for /sumo make
        default: op
      sumo.cmd.remove:
        description: Permission for /sumo delete
        default: op
      sumo.cmd.set:
        description: Permission for /sumo set
        default: op
      sumo.cmd.arenas:
        description: Permission for /sumo arenas
        default: op
      sumo.cmd.join:
        description: Permission for /sumo join
        default: true
